server: 
   port: 7002

spring:
  autoconfigure:
    exclude:
    #- org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    #- org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  security:
    user:
      name: fatih
      password: pass
      roles:
      - manager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testfa
    username: root    
    password: my-secret-pw
  jpa:
    database-platform: org.springframework.orm.jpa.vendor.Database.MYSQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect : org.hibernate.dialect.MySQL8Dialect

        
